version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    restart: always
    depends_on: 
      - traefik
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    labels:
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`docker`) || Host(`docker.local.texasosbornes.com`)"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.services.portaienr.loadbalancer.server.scheme=http"

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "./etc/traefik/traefik.toml:/etc/traefik/traefik.toml:r"

volumes:
  portainer_data:
    driver: local
