[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.metrics]
    address = ":8082"

[log]
  level = "DEBUG"
  format = "json"

[api]
  insecure = true
  dashboard = true

[ping]

[providers.file]
  directory = "/conf"
  watch = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

#  swarmMode = true
#  swarmModeRefreshSeconds = 10

# exposedByDefault = false
  watch = true
#  network = "net"

